name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
#  lint:
#    runs-on: windows-latest  # Use Windows runner for linting
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Run Lint
#        run: .\gradlew lintDebug  # Use Windows-style command
#
#      - name: Upload lint report
#        uses: actions/upload-artifact@v3
#        with:
#          name: lint.html
#          path: app\build\reports\lint-results-debug.html  # Windows-style path
#
#  unit-test:
#    needs: [lint]  # This makes the 'unit-test' job depend on the 'lint' job
#    runs-on: windows-latest  # Use Windows runner for unit tests
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Run unit tests
#        run: .\gradlew testDebugUnitTest  # Run unit tests specifically on Windows
#
#      - name: Upload test reportgradle -v
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-report
#          path: app\build\reports\tests\testDebugUnitTest\index.html  # Path to unit test report



      sonarcloud:
       runs-on: ubuntu-latest
       steps:
        - name: Checkout the code
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17
            distribution: 'temurin'

        - name: Grant execute permission to gradlew
          run: chmod +x ./gradlew

        - name: SonarCloud Scan
          run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}  # Auto-filled GitHub token

        - name: Upload SonarCloud reports
          uses: actions/upload-artifact@v3
          with:
            name: sonarcloud-report
            path: app/build/reports/sonar


