name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Check lint report permissions
        run: ls -l app/build/reports

      - name: Upload html test report
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: app/build/reports/lint-results-debug.html
