name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  lint:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # You can use AdoptOpenJDK or Eclipse Temurin

      - name: Verify Java version
        run: java -version  # Verify Java 17 is being used

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew  # This is for Linux/Mac, Windows does not need it.

      - name: Run Lint
        run: ./gradlew lintDebug  # Run linting

      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]  # This makes the 'unit-test' job depend on the 'lint' job
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Ensure Java 17 is installed

      - name: Verify Java version
        run: java -version  # Check that Java 17 is set up correctly

      - name: Run tests
        run: ./gradlew testDebugUnitTest  # Run unit tests

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: app/build/reports/tests/testDebugUnitTest/index.html  # Path to test report
